<center>
    <h1 style="font-weight: bold;">
    Binary Classification from Tabular Data</h1>
</center>

## **Deskripsi**

Pada kompetisi ini, peserta diminta untuk memprediksi **< label >**. Data yang diberikan adalah : 
* **< feature 1 >** : **< feature1_description >**
* **< feature 2 >** : **< feature2_description >**
* ...

## **Library Import**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Preprocessing
from utils.preprocessing import (
    FeatureOutliersHandling,
    FeatureImputer,
    FeatureResampling,
    FeatureLabelEncoder,
    FeatureDiscretizer,
    FeatureRareCategoriesGrouping,
    FeaturePolynomialAdder,
    FeaturePowerTransformer,
    FeatureGroupingNumeric,
    FeatureDimensionReducer,
    FeatureEncoder,
    FeatureScaler,
)

import warnings
warnings.filterwarnings('ignore')

## **Data Loading**

In [2]:
data_path = './data'

**Train**

In [3]:
# TODO: define initial dataframes
initial_df = pd.read_csv(f'{data_path}/EV_data.csv')
# -----------------------------------

initial_df

,read_date,interval_1,interval_2,interval_3,interval_4,interval_5,interval_6,interval_7,interval_8,interval_9,...,interval_41,interval_42,interval_43,interval_44,interval_45,interval_46,interval_47,interval_48,id,label
0,3/1/2021,0.0625,0.0500,0.0687,0.0750,0.0687,0.0500,0.0625,0.0687,0.0687,...,0.0812,0.0687,0.0687,0.0562,0.0562,0.0687,0.0687,0.0625,1,1
1,3/2/2021,0.0625,0.0500,0.0687,0.0625,0.0625,0.0562,0.0562,0.0625,0.0687,...,0.1375,0.0750,0.0687,0.0625,0.0625,0.0562,0.0625,0.0625,1,1
2,3/3/2021,0.0625,0.0687,0.0500,0.0562,0.0687,0.0625,0.0625,0.0625,0.0500,...,0.1875,0.1062,0.0750,0.0687,0.0687,0.0625,0.0562,0.0562,1,1
3,3/4/2021,0.0625,0.0625,0.0687,0.0500,0.0562,0.0625,0.0625,0.0625,0.0562,...,0.1125,0.0875,0.0687,0.0625,0.0562,0.0625,0.0625,0.0687,1,1
4,3/5/2021,0.0625,0.0625,0.0500,0.0625,0.0687,0.0625,0.0687,0.0562,0.0500,...,0.0812,0.0562,0.0687,0.0625,0.0625,0.0625,0.0562,0.0500,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4043,3/31/2021 0:00,0.2125,0.2000,0.1625,0.1750,0.2375,0.2125,0.1875,0.1750,0.2000,...,0.3375,0.3875,0.3375,0.3875,0.2500,0.5125,0.4750,0.2000,57,0
4044,4/1/2021 0:00,0.1625,0.1625,0.1500,0.1500,0.2000,0.1750,0.1625,0.1625,0.1500,...,0.2375,0.2000,0.2125,0.2000,0.2000,0.2875,0.1875,0.2250,57,0
4045,4/2/2021 0:00,0.1625,0.2000,0.2125,0.1625,0.1625,0.1375,0.1500,0.1250,0.1875,...,0.2500,0.2750,0.3750,0.3375,0.3250,0.2625,0.3000,0.3500,57,0
4046,4/3/2021 0:00,0.2250,0.2250,0.1625,0.1750,0.1750,0.1500,0.1500,0.2125,0.1625,...,0.3375,0.4000,0.3500,0.2625,0.4000,0.3375,0.8375,0.6625,57,0
4047,4/4/2021 0:00,0.2000,0.1625,0.1625,0.2000,0.1500,0.1500,0.1750,0.1750,0.1375,...,0.5250,0.4125,0.4000,0.4500,0.3625,0.6500,1.3500,0.7875,57,0

**Test**

In [4]:
# # TODO: define test dataframe
# test_features_df = pd.read_csv(f'{data_path}/test_features.csv')

# submisssion_ids = test_features_df['ID']

# test_features_df = test_features_df.drop(columns=['ID'])
# # -------------------------------------

# test_features_df = test_features_df.reindex(sorted(test_features_df.columns), axis=1)

# test_features_df

**Define Target and Features**

In [5]:
# TODO: define which columns are target labels
label = 'label'
# -----------------------------------
# TODO: define which columns are categorical and which are numerical features
categorical_features = ['id']

# get all columns with float64 and int64 data types
numerical_features = initial_df.select_dtypes(include=['float64']).columns
# -----------------------------------

## **Data Preparation**

### **Drop Unnecessary Columns [TENTATIVE]**

In [6]:
# TODO: define columns to drop
columns_to_drop = ['read_date']
# -----------------------------------

categorical_features = [col for col in categorical_features if col not in columns_to_drop]
numerical_features = [col for col in numerical_features if col not in columns_to_drop]

### **Drop Duplicates**

In [7]:
print('Row count for initial data before removing duplicates:', len(initial_df))
initial_df.drop_duplicates(inplace=True)
print('Row count for initial data after removing duplicates:', len(initial_df))
initial_df.reset_index(drop=True, inplace=True) # Reset the index after dropping duplicates

Row count for initial data before removing duplicates: 4048
Row count for initial data after removing duplicates: 4048

In [8]:
initial_df = initial_df.drop(columns=columns_to_drop)
# test_features_df = test_features_df.drop(columns=columns_to_drop)

### **Change Wrong Value to NaN [Tentative]**

In [9]:
# wrong_values = '5'

# initial_df['pendidikan'] = initial_df['pendidikan'].replace(wrong_values, np.nan)
# initial_df['status_pernikahan'] = initial_df['status_pernikahan'].replace(wrong_values, np.nan)

# test_features_df['pendidikan'] = test_features_df['pendidikan'].replace(wrong_values, np.nan)
# test_features_df['status_pernikahan'] = test_features_df['status_pernikahan'].replace(wrong_values, np.nan)

#### **Check Similarity Columns between Train and Test**

In [10]:
def is_same_cols(df1: pd.DataFrame, df2: pd.DataFrame, label: str):
    """
    Function to check if two DataFrames have the same columns, excluding the label column if it exists.
    
    Parameters:
    - df1: First DataFrame
    - df2: Second DataFrame
    - label: The name of the label column to exclude from the comparison (default is 'label').
    
    Returns:
    - Boolean value indicating whether the columns are the same, excluding the label column
    """
    # Exclude the label column if it exists in either DataFrame
    df1_cols = df1.columns.drop(label) if label in df1.columns else df1.columns
    df2_cols = df2.columns.drop(label) if label in df2.columns else df2.columns

    # Compare the remaining columns
    return df1_cols.equals(df2_cols)

In [11]:
# print('Initial and test features have the same columns:', is_same_cols(initial_df, test_features_df, label))

### **Convert read_date**

In [12]:
# # initial_df['read_date'] = pd.to_datetime(initial_df['read_date'], format='%m/%d/%Y')

# initial_df['read_date'] = initial_df['read_date'].str.replace(' 0:00', '')
# initial_df['read_date'] = pd.to_datetime(initial_df['read_date'], format='%m/%d/%Y')

In [13]:
# initial_df['day_of_week_num'] = initial_df['read_date'].dt.day_of_week
# initial_df['day_of_month'] = initial_df['read_date'].dt.day
# initial_df['month'] = initial_df['read_date'].dt.month
# initial_df.drop(columns=['read_date'], inplace=True)
# initial_df

### **Train Test Split**

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X = initial_df.drop(columns=[label])
y = initial_df[label]

# X_test = test_features_df

In [16]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

print("Jumlah data:", len(initial_df))
print("Jumlah data train:", len(X_train))
print("Jumlah data validasi:", len(X_val))

Jumlah data: 4048
Jumlah data train: 3238
Jumlah data validasi: 810

In [17]:
print("X_train and X_val have the same columns:", is_same_cols(X_train, X_val, label))
# print("X_test has the same columns as X_train:", is_same_cols(X_train, test_features_df, label))

X_train and X_val have the same columns: True

### **Change Outliers Value to NaN [TENTATIVE: Based on EDA Boxplot]**

#### **Outlier : IForest**

In [18]:
outlier_handler_iforest = FeatureOutliersHandling(
    numerical_features=numerical_features,
    contamination=0.05, 
    outlier_method='iforest'
)

In [19]:
# X_train.isnull().sum()

In [20]:
# X_train = outlier_handler_iforest.fit_transform(X_train)
# X_train.isnull().sum()

#### **Outlier : IQR-ZScore**

In [21]:
# outlier_handler_iqr_zscore = FeatureOutliersHandling(
#     numerical_features=numerical_features, 
#     contamination=0.05, 
#     outlier_method='iqr-zscore'
# )

# outlier_handler_iqr_zscore.plot_boxplots_for_numerical_features(X_train)

In [22]:
# X_train.isnull().sum()

In [23]:
# X_train = outlier_handler_iqr_zscore.fit_transform(X_train, numerical_features_to_handle=numerical_features)

# X_train.isnull().sum()

### **Impute Data**

In [24]:
imputer = FeatureImputer(
    numerical_features=numerical_features,
    categorical_features=categorical_features,
    int_num_features=numerical_features, # depends on the dataset
    imputer_type='iterative',
    num_strategy='mean',
    cat_strategy='most_frequent'
)

In [25]:
X_train.isnull().sum()

interval_1     0
interval_2     0
interval_3     0
interval_4     0
interval_5     0
interval_6     0
interval_7     0
interval_8     0
interval_9     0
interval_10    0
interval_11    0
interval_12    0
interval_13    0
interval_14    0
interval_15    0
interval_16    0
interval_17    0
interval_18    0
interval_19    0
interval_20    0
interval_21    0
interval_22    0
interval_23    0
interval_24    0
interval_25    0
interval_26    0
interval_27    0
interval_28    0
interval_29    0
interval_30    0
interval_31    0
interval_32    0
interval_33    0
interval_34    0
interval_35    0
interval_36    0
interval_37    0
interval_38    0
interval_39    0
interval_40    0
interval_41    0
interval_42    0
interval_43    0
interval_44    0
interval_45    0
interval_46    0
interval_47    0
interval_48    0
id             0
dtype: int64

In [26]:
# X_train = imputer.fit_transform(X_train)
# X_val = imputer.transform(X_val)
# # X_test = imputer.transform(X_test)

# X_train.isnull().sum()

### **Resampling [TENTATIVE: Based on Label Distribution]**

In [27]:
# sampling_strategy = {1: 786, 2: 786}

# resampler = FeatureResampling(
#     resampling_method='oversampling',
#     categorical_features=categorical_features,
#     sampling_strategy=sampling_strategy,
#     random_state=42
# )

In [28]:
# resampler.plot_class_count(y_train, title="Distribusi Kelas Sebelum Oversampling")

In [29]:
# X_train, y_train = resampler.fit_transform(X_train, y_train)

# resampler.plot_class_count(y_train, title="Distribusi Kelas Setelah Oversampling")

### **Encode Label [TENTATIVE: If Label is Categorical Object]**

In [30]:
# label_encoder = FeatureLabelEncoder()

# y_train = label_encoder.fit_transform(y_train)
# y_val = label_encoder.transform(y_val)

# label_encoder.get_encoding_map()

### **Numerical Features : Binning [OPTIONAL: If Necessary]**

In [31]:
discretizer = FeatureDiscretizer(
    n_bins=5,
    encode='ordinal',
    strategy='uniform',
    numerical_features_to_discretize=['tahun_kelahiran']
)

In [32]:
# X_train

In [33]:
# X_train = discretizer.fit_transform(X_train)
# X_val = discretizer.transform(X_val)
# X_test = discretizer.transform(X_test)
# discretizer.get_bin_edges()
# X_train

### **Categorical Features : Rare Categories Grouping [OPTIONAL: If Column has Rare Categories]**

In [34]:
# categorical_features_to_group = ['status_pernikahan', 'pendidikan']

# rare_grouping = FeatureRareCategoriesGrouping(
#     categorical_features=categorical_features_to_group,
#     threshold=0.1,
#     rare_label='Rare'
# )

In [35]:
# for feature in categorical_features_to_group:
#     print(f"Value counts for {feature} before rare category grouping:")
#     print(X_train[feature].value_counts(normalize=True))

In [36]:
# X_train = rare_grouping.fit_transform(X_train)
# X_val = rare_grouping.transform(X_val)
# X_test = rare_grouping.transform(X_test)

# for feature in categorical_features_to_group:
#     print(f"Value counts for {feature} after rare category grouping:")
#     print(X_train[feature].value_counts(normalize=True))

### **Numerical Features : Polynomial Features [OPTIONAL: If Necessary]**

In [37]:
# columns_to_poly = [
#     'pembelian_diskon',
#     'pembelian_toko',
#     'pembelian_web'
# ]

# poly_features_adder = FeaturePolynomialAdder(
#     degree=2,
#     interaction_only=False,
#     include_bias=False,
#     columns=columns_to_poly
# )

In [38]:
# X_train.columns

In [39]:
# X_train = poly_features_adder.fit_transform(X_train)
# X_val = poly_features_adder.transform(X_val)
# X_test = poly_features_adder.transform(X_test)

# X_train.columns

### **Numerical Features : Power Transform [OPTIONAL: If Necessary]**

In [40]:
# numerical_features_to_transform = [
#     'belanja_buah',
#     'belanja_daging',
#     'belanja_ikan',
#     'belanja_kue',
# ]

# # Inisialisasi transformer
# power_transformer = FeaturePowerTransformer(
#     method='yeo-johnson',
#     standardize=True,
#     columns=numerical_features_to_transform
# )

In [41]:
# # Data sebelum transformasi
# X_train_before = X_train[numerical_features_to_transform]

# # Fit dan transform data
# X_train = power_transformer.fit_transform(X_train)
# X_val = power_transformer.transform(X_val)
# X_test = power_transformer.transform(X_test)

# # Data setelah transformasi
# X_train_after = X_train[numerical_features_to_transform]

# # Plot distribusi sebelum dan sesudah transformasi
# power_transformer.plot_kde_hist_before_after(X_train_before, X_train_after)

# # Dapatkan nilai lambda untuk setiap fitur
# print("Lambda values for power transformation:")
# print(power_transformer.get_lambdas())

### **Numerical Features : Grouping (min,max,mean,median,std) [OPTIONAL: If Necessary]**

In [42]:
# numerical_features_to_grouping = [
#     'belanja_buah', 
#     'belanja_daging', 
#     'belanja_ikan', 
#     'belanja_kue'
# ]

# grouping_transformer = FeatureGroupingNumeric(
#     numerical_features_to_grouping=numerical_features_to_grouping,
#     aggregations=['min', 'max', 'mean', 'median', 'std'],
#     columns_name='belanja'
# )

In [43]:
# X_train.columns

In [44]:
# X_train = grouping_transformer.fit_transform(X_train)
# X_val = grouping_transformer.transform(X_val)
# X_test = grouping_transformer.transform(X_test)

# X_train.columns

### **Numerical Features : Dimensionality Reduction [OPTIONAL: If Necessary]**

#### **PCA**

In [45]:
# numeric_features_pca = ['belanja_buah','belanja_daging','belanja_ikan','belanja_kue']
# n_components = 4

# reducer = FeatureDimensionReducer(
#     method='pca',
#     n_components=n_components,
#     numeric_features_to_reduce=numeric_features_pca,
#     column_names='belanja_pca'
# )

In [46]:
# X_train

In [47]:
# X_train = reducer.fit_transform(X_train) 

# print(f"Explained variance ratio for {n_components} components:\n", reducer.get_variance_ratio())

In [48]:
# X_val_pca = reducer.transform(X_val)
# # X_test_pca = reducer.transform(X_test)

In [49]:
X_train

,interval_1,interval_2,interval_3,interval_4,interval_5,interval_6,interval_7,interval_8,interval_9,interval_10,...,interval_40,interval_41,interval_42,interval_43,interval_44,interval_45,interval_46,interval_47,interval_48,id
4004,1.0625,0.6750,0.9875,1.0000,0.8250,0.7125,0.8000,0.9625,1.0000,0.9875,...,0.7625,0.7375,0.9250,0.7625,0.7875,1.0125,1.3375,0.9750,0.8000,57
3240,0.1500,0.1500,0.1437,0.1437,0.1500,0.1437,0.1437,0.1500,0.1187,0.4750,...,0.1812,0.1750,0.1312,0.2437,0.1500,0.1437,0.1500,0.1500,0.2312,80
2838,0.0630,0.0620,0.0620,0.0610,0.0620,0.0630,0.0650,0.0650,0.0630,0.0640,...,0.0680,0.0800,0.0610,0.0610,0.0600,0.0550,0.0570,0.0570,0.0530,77
3426,0.0940,0.0970,0.0820,0.0890,0.0960,0.0820,0.0980,0.0920,0.0760,0.0980,...,0.1920,0.1610,0.1740,0.1130,0.0970,0.1060,0.1180,1.1510,1.5080,71
3929,0.2090,0.1850,0.2950,0.1570,0.1270,0.1670,0.1430,0.1440,0.1610,0.1220,...,0.7390,0.7530,0.7180,0.5670,0.5520,0.3750,0.1820,0.1520,0.1640,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,0.0000,0.0062,0.0000,0.0000,0.0000,0.0062,0.0000,0.0000,0.0062,0.0000,...,0.0000,0.0000,0.0062,0.0000,0.0000,0.0062,0.0000,0.0000,0.0000,32
1047,0.0375,0.0312,0.0250,0.0437,0.0250,0.0250,0.0437,0.0250,0.0250,0.0437,...,0.4312,0.3625,0.1000,0.1187,0.0750,0.1125,0.0375,0.0187,0.0500,23
641,0.6187,0.5062,0.4500,0.4625,0.4812,0.4750,0.4937,0.4625,0.5937,0.4875,...,3.8750,3.8187,3.9437,3.7312,3.8000,3.8812,3.7625,3.7937,3.6812,36
379,0.0875,0.0937,0.1000,0.1000,0.0937,0.1187,0.1562,0.1187,0.1250,0.0875,...,0.1750,0.1500,0.2000,0.3187,0.2937,0.1187,0.1125,0.1187,0.1062,31
465,0.1250,0.1187,0.1312,0.1437,0.1375,0.1312,0.1125,0.1250,0.1437,0.1437,...,0.4250,0.2750,0.2812,0.2625,0.2437,0.2187,0.2375,0.1687,0.1125,33

#### **LDA**

In [50]:
# numeric_features_lda = ['pembelian_diskon','pembelian_toko','pembelian_web']
# n_components = 2

# reducer = FeatureDimensionReducer(
#     method='lda',
#     n_components=n_components,
#     numeric_features_to_reduce=numeric_features_lda,
#     column_names='pembelian_lda'
# )

In [51]:
# X_train

In [52]:
# X_train = reducer.fit_transform(X_train, y_train)
# X_val_lda = reducer.transform(X_val)
# X_test_lda = reducer.transform(X_test)

In [53]:
# X_train

### **Encode Categorical Features**

In [54]:
# # TODO: Define the ordinal features from the categorical features
# ordinal_features_dict = {
#     # 'pendidikan': ['SMP', 'SMA', 'Sarjana', 'Magister', 'Doktor'],
#     'status_pernikahan': ['Rencana Menikah', 'Menikah', 'Sendiri', 'Cerai', 'Cerai Mati']
# }
# # -----------------------------------

# # Define the nominal categorical features for one-hot encoding
# one_hot_features = ['pendidikan']

# encoder = FeatureEncoder(
#     ordinal_features_dict=ordinal_features_dict,
#     one_hot_features=one_hot_features
# )

In [55]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3238 entries, 4004 to 465
Data columns (total 49 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   interval_1   3238 non-null   float64
 1   interval_2   3238 non-null   float64
 2   interval_3   3238 non-null   float64
 3   interval_4   3238 non-null   float64
 4   interval_5   3238 non-null   float64
 5   interval_6   3238 non-null   float64
 6   interval_7   3238 non-null   float64
 7   interval_8   3238 non-null   float64
 8   interval_9   3238 non-null   float64
 9   interval_10  3238 non-null   float64
 10  interval_11  3238 non-null   float64
 11  interval_12  3238 non-null   float64
 12  interval_13  3238 non-null   float64
 13  interval_14  3238 non-null   float64
 14  interval_15  3238 non-null   float64
 15  interval_16  3238 non-null   float64
 16  interval_17  3238 non-null   float64
 17  interval_18  3238 non-null   float64
 18  interval_19  3238 non-null   float64
 19  interval_20  3238 non-null   float64
 20  interval_21  3238 non-null   float64
 21  interval_22  3238 non-null   float64
 22  interval_23  3238 non-null   float64
 23  interval_24  3238 non-null   float64
 24  interval_25  3238 non-null   float64
 25  interval_26  3238 non-null   float64
 26  interval_27  3238 non-null   float64
 27  interval_28  3238 non-null   float64
 28  interval_29  3238 non-null   float64
 29  interval_30  3238 non-null   float64
 30  interval_31  3238 non-null   float64
 31  interval_32  3238 non-null   float64
 32  interval_33  3238 non-null   float64
 33  interval_34  3238 non-null   float64
 34  interval_35  3238 non-null   float64
 35  interval_36  3238 non-null   float64
 36  interval_37  3238 non-null   float64
 37  interval_38  3238 non-null   float64
 38  interval_39  3238 non-null   float64
 39  interval_40  3238 non-null   float64
 40  interval_41  3238 non-null   float64
 41  interval_42  3238 non-null   float64
 42  interval_43  3238 non-null   float64
 43  interval_44  3238 non-null   float64
 44  interval_45  3238 non-null   float64
 45  interval_46  3238 non-null   float64
 46  interval_47  3238 non-null   float64
 47  interval_48  3238 non-null   float64
 48  id           3238 non-null   int64
dtypes: float64(48), int64(1)
memory usage: 1.2 MB

In [56]:
# X_train = encoder.fit_transform(X_train)
# X_val = encoder.transform(X_val)
# X_test = encoder.transform(X_test)

# X_train.info()

In [57]:
X_train

,interval_1,interval_2,interval_3,interval_4,interval_5,interval_6,interval_7,interval_8,interval_9,interval_10,...,interval_40,interval_41,interval_42,interval_43,interval_44,interval_45,interval_46,interval_47,interval_48,id
4004,1.0625,0.6750,0.9875,1.0000,0.8250,0.7125,0.8000,0.9625,1.0000,0.9875,...,0.7625,0.7375,0.9250,0.7625,0.7875,1.0125,1.3375,0.9750,0.8000,57
3240,0.1500,0.1500,0.1437,0.1437,0.1500,0.1437,0.1437,0.1500,0.1187,0.4750,...,0.1812,0.1750,0.1312,0.2437,0.1500,0.1437,0.1500,0.1500,0.2312,80
2838,0.0630,0.0620,0.0620,0.0610,0.0620,0.0630,0.0650,0.0650,0.0630,0.0640,...,0.0680,0.0800,0.0610,0.0610,0.0600,0.0550,0.0570,0.0570,0.0530,77
3426,0.0940,0.0970,0.0820,0.0890,0.0960,0.0820,0.0980,0.0920,0.0760,0.0980,...,0.1920,0.1610,0.1740,0.1130,0.0970,0.1060,0.1180,1.1510,1.5080,71
3929,0.2090,0.1850,0.2950,0.1570,0.1270,0.1670,0.1430,0.1440,0.1610,0.1220,...,0.7390,0.7530,0.7180,0.5670,0.5520,0.3750,0.1820,0.1520,0.1640,83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
437,0.0000,0.0062,0.0000,0.0000,0.0000,0.0062,0.0000,0.0000,0.0062,0.0000,...,0.0000,0.0000,0.0062,0.0000,0.0000,0.0062,0.0000,0.0000,0.0000,32
1047,0.0375,0.0312,0.0250,0.0437,0.0250,0.0250,0.0437,0.0250,0.0250,0.0437,...,0.4312,0.3625,0.1000,0.1187,0.0750,0.1125,0.0375,0.0187,0.0500,23
641,0.6187,0.5062,0.4500,0.4625,0.4812,0.4750,0.4937,0.4625,0.5937,0.4875,...,3.8750,3.8187,3.9437,3.7312,3.8000,3.8812,3.7625,3.7937,3.6812,36
379,0.0875,0.0937,0.1000,0.1000,0.0937,0.1187,0.1562,0.1187,0.1250,0.0875,...,0.1750,0.1500,0.2000,0.3187,0.2937,0.1187,0.1125,0.1187,0.1062,31
465,0.1250,0.1187,0.1312,0.1437,0.1375,0.1312,0.1125,0.1250,0.1437,0.1437,...,0.4250,0.2750,0.2812,0.2625,0.2437,0.2187,0.2375,0.1687,0.1125,33

### **Feature Scaling**

Use StandardScaler if the data is normally distributed, otherwise use MinMaxScaler.

In [58]:
scaler = FeatureScaler()

X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
# # X_test = scaler.transform(X_test)

In [59]:
normal_features, non_normal_features = scaler.get_scaler_columns()

print("Normal Features:", normal_features)
print("Non-Normal Features:", non_normal_features)

Normal Features: []
Non-Normal Features: ['interval_1', 'interval_2', 'interval_3', 'interval_4', 'interval_5', 'interval_6', 'interval_7', 'interval_8', 'interval_9', 'interval_10', 'interval_11', 'interval_12', 'interval_13', 'interval_14', 'interval_15', 'interval_16', 'interval_17', 'interval_18', 'interval_19', 'interval_20', 'interval_21', 'interval_22', 'interval_23', 'interval_24', 'interval_25', 'interval_26', 'interval_27', 'interval_28', 'interval_29', 'interval_30', 'interval_31', 'interval_32', 'interval_33', 'interval_34', 'interval_35', 'interval_36', 'interval_37', 'interval_38', 'interval_39', 'interval_40', 'interval_41', 'interval_42', 'interval_43', 'interval_44', 'interval_45', 'interval_46', 'interval_47', 'interval_48', 'id']

In [60]:
# X_train

## **Modelling**

### Logistic Regression

In [61]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
# import xgboost as xgb
from sklearn.model_selection import KFold, train_test_split
from sklearn.metrics import accuracy_score

In [62]:
import numpy as np
# Define fungsi sigmoid
def sigmoid(x):
    # Merubah input menjadi probabilitas di range (0,1)
    return 1/(1+np.exp(-x))

# Define Kelas untuk LogReg
class LogisticRegression():
    # Init konstruktor dengan params learning rate dan jumlah iterasi
    def __init__(self, lr=0.001, n_iters=200):
        self.lr = lr
        self.n_iters = n_iters
        self.weights = None
        self.bias = None

    # fit dengan data train 
    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        # Loop untuk update parameter sebanyak n_iters
        for _ in range(self.n_iters):
            # hitung linear prediction
            linear_pred = np.dot(X, self.weights) + self.bias
            # masukkan ke sigmoid
            predictions = sigmoid(linear_pred)

           # cari gradien untuk weight dan bias (optimization)
            dw = (1/n_samples) * np.dot(X.T, (predictions - y))
            db = (1/n_samples) * np.sum(predictions-y)
            
            # update weight dan bias
            self.weights = self.weights - self.lr*dw
            self.bias = self.bias - self.lr*db

    # prediksi data test
    def predict(self, X):
        linear_pred = np.dot(X, self.weights) + self.bias
        y_pred = sigmoid(linear_pred)
        # jika probabilitas > 0.5, maka kelas 1, jika tidak kelas 0
        class_pred = [0 if y<=0.5 else 1 for y in y_pred]
        return class_pred

In [63]:
clf = LogisticRegression(lr=0.01)
clf.fit(X_train,y_train)
y_pred = clf.predict(X_val)

## Evaluation

In [64]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report

In [65]:
print(classification_report(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.58      1.00      0.74       405
           1       1.00      0.29      0.45       405

    accuracy                           0.64       810
   macro avg       0.79      0.64      0.59       810
weighted avg       0.79      0.64      0.59       810